version: "2"
services:
  # apigateway:
  #   build: './apigateway'
  #   ports:
  #     - "9000:9000"
  #   depends_on: 
  #     - mongo
  items:
    build: ./items
    ports:
      - "8080:8080"
    depends_on:
      - mongo_items
  users:
    build: ./users
    ports:
      - "8090:8090"
    depends_on:
      - mongo_users
  categories:
    build: ./categories
    ports:
      - "8060:8060"
    depends_on:
      - mongo_categories
  reviews:
    build: ./reviews
    ports:
      - "8050:8050"
    depends_on:
      - mongo_reviews
  mongo_items:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data/db-mongo_items:/data/db
  mongo_users:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db-mongo_users:/data/db
  mongo_categories:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - ./data/db-mongo_categories:/data/db
  mongo_reviews:
    image: mongo
    ports:
      - "27016:27017"
    volumes:
      - ./data/db-mongo_reviews:/data/db
  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   volumes:
  #     - '.:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true


