version: "2"
services:
  # apigateway:
  #   build: './apigateway'
  #   ports:
  #     - "9000:9000"
  #   depends_on: 
  #     - mongo
  items:
    build: ./items
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27018:27018"
  users:
    build: ./users
    ports:
      - "8090:8090"
    depends_on:
      - mongo
  mongo_users:
    image: mongo
    ports:
      - "27017:27017"
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

